name: list-matched-workflows-action
description: List matched workflows against the changed files of the pull request.

inputs:
  workflows:
    description: Glob pattern to match workflow files
    required: true
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
